import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AVIS Plus',
  description: 'Generated by AVIS Engine',
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div>{children}</div>
}
