import { Footer } from '@/components/event-page-component/Footer'
import Navigation from '@/components/page-components/Navigation'
import { EventsProvider } from '@/hooks/EventsProvider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AVIS Challenge',
  description: 'Generated by AVIS Engine',
  icons: {
    icon: 'https://kbgnpdzggogidjwifiuq.supabase.co/storage/v1/object/public/avis/logo/avis-mono-dark.png',
    shortcut:
      'https://kbgnpdzggogidjwifiuq.supabase.co/storage/v1/object/public/avis/logo/avis-mono-dark.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navItems = [
    {
      name: 'Products',
      link: '#products',
      children: [
        { name: 'AVIS Events', link: '/avis-events' },
        { name: 'AVIS Challenge', link: '/avis-challenge' },
        { name: 'AVIS Plus +', link: '/avis-plus' },
        { name: 'AVIS Community', link: '/avis-community' },
      ],
    },
    { name: 'Competitions', link: '#competitions' },
    { name: 'Discover', link: '#discover' },
    { name: 'Upcoming Events', link: '#upcoming-events' },
  ]

  const logo =
    'https://kbgnpdzggogidjwifiuq.supabase.co/storage/v1/object/public/avis/logo/avis-mono-dark.png'

  return (
    <EventsProvider>
      <div className='min-h-screen bg-black text-white'>
        <Navigation logo={logo} navItems={navItems} />
        <main className='max-w-6xl mx-auto border-l border-r border-white/10 mt-17 min-h-screen'>
          {children}
        </main>
        <Footer />
      </div>
    </EventsProvider>
  )
}
