import DownloadSection from '@/components/page-components/DownloadSection'
import { Footer } from '@/components/event-page-component/Footer'
import Navigation from '@/components/page-components/Navigation'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AVIS Engine',
  description: 'Generated by AVIS Engine',
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navItems = [
    {
      name: 'Products',
      link: '#products',
      children: [
        { name: 'AVIS Events', link: '/avis-events' },
        { name: 'AVIS Challenge', link: '/avis-challenge' },
        { name: 'AVIS Plus +', link: '/avis-plus' },
        { name: 'AVIS Community', link: '/avis-community' },
      ],
    },
  ]

  const logo =
    'https://kbgnpdzggogidjwifiuq.supabase.co/storage/v1/object/public/avis/logo/avis-mono-dark.png'

  return (
    <div className=''>
      <Navigation logo={logo} navItems={navItems} />
      {children}
      <DownloadSection />
      <Footer />
    </div>
  )
}
