import DownloadSection from '@/components/page-components/DownloadSection'
import Footer from '@/components/page-components/Footer'
import Navigation from '@/components/page-components/Navigation'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className=''>
      <Navigation />
      {children}
      <DownloadSection />
      <Footer />
    </div>
  )
}
